searchengines = {'DEFAULT': 'http://www.google.com/search?q={}',
    'w' : 'http://www.wikipedia.org/w/index.php?title=Special:Search&search={}',
    'y' : 'http://www.youtube.com/results?search_query={}',
    'i' : 'https://www.google.com/images?q={}',
    'gm' : 'https://www.google.com/maps?q={}',
    '5' : 'https://500px.com/search?q={}',
    'vk' : 'https://www.verkkokauppa.com/fi/search/?q={}',
    'r' : 'https://reddit.com/r/{}',
    'R' : 'https://www.reddit.com/search?q={}',
    'ddg' : 'https://duckduckgo.com/?q={}',
    'e' : 'https://eepos.finna.fi/Search/Results?lookfor={}&type=AllFields',
    'so' : 'https://stackoverflow.com/search?q={}',
    'gh' : 'https://github.com/search?q={}'}
